[package]
authors = ["Jarkko Sakkinen <jarkko@kernel.org>"]
description = "TPM 2.0 marshaler/unmarshaler"
edition = "2021"
homepage = "https://git.kernel.org/pub/scm/linux/kernel/git/jarkko/tpm2-protocol.git/about"
license = "MIT OR Apache-2.0"
name = "tpm2-protocol"
readme = "README.md"
repository = "https://git.kernel.org/pub/scm/linux/kernel/git/jarkko/tpm2-protocol.git"
rust-version = "1.81"
version = "0.14.3"

[dev-dependencies]

[dependencies]

[[test]]
name = "return_code"
path = "tests/return_code.rs"
harness = false

[[test]]
name = "message"
path = "tests/message.rs"
harness = false
