[package]
name = "tpm2sh"
description = "TPM 2.0 shell"
version = "0.11.12"
license = "GPL-3.0-or-later"
homepage = "https://git.kernel.org/pub/scm/linux/kernel/git/jarkko/tpm2sh.git/about/?h=main"
repository = "https://git.kernel.org/pub/scm/linux/kernel/git/jarkko/tpm2sh.git"
authors = ["Jarkko Sakkinen <jarkko.sakkinen@opinsys.com>"]
edition = "2021"
rust-version = "1.79"
readme = "README.md"

[lib]
name = "cli"
path = "src/lib.rs"

[[bin]]
name = "tpm2sh"
path = "src/main.rs"

[dependencies]
aes = "0.8"
base64 = "0.22"
cfb-mode = "0.8"
cipher = "0.4"
clap = { version = "4.5", features = ["derive"] }
ctrlc = "3.4"
directories = "5.0"
env_logger = "0.11"
hex = "0.4"
hmac = "0.12"
indicatif = "0.17"
log = "0.4"
nix = { version = "0.29", features = ["fs"] }
nom = "7.1"
num-bigint = "0.4"
num-traits = "0.2"
p256 = { version = "0.13", features = ["ecdh"] }
p384 = { version = "0.13", features = ["ecdh"] }
p521 = { version = "0.13", features = ["ecdh"] }
pem = "3.0"
polling = "3.7"
rand = "0.8"
rasn = "0.26"
rasn-derive = "0.26"
rsa = { version = "0.9", features = ["sha1", "sha2"] }
sha1 = "0.10"
sha2 = "0.10"
strum = { version = "0.26", features = ["derive"] }
tabled = { version = "0.15", features = ["ansi"] }
thiserror = "1.0"
tpm2-protocol = "0.10"

