[workspace]
resolver = "3"
members = [
    "crates/crypto",
    "crates/device",
    "crates/policy-language",
    "crates/protocol",
    "crates/sh",
    "crates/tpmkey",
    "crates/vtpm",
]

[workspace.package]
authors = ["Jarkko Sakkinen <jarkko@kernel.org>"]
edition = "2024"
homepage = "https://github.com/jarkkojs/tpm2-library"
repository = "https://github.com/jarkkojs/tpm2-library"
rust-version = "1.95"
version = "1.2.3"

[workspace.dependencies]
tpm2-crypto = { version = "1.2.3", path = "crates/crypto" }
tpm2-device = { version = "1.2.3", path = "crates/device" }
tpm2-policy-language = { version = "1.2.3", path = "crates/policy-language" }
tpm2-protocol = { version = "1.2.3", path = "crates/protocol" }
tpm2-tpmkey = { version = "1.2.3", path = "crates/tpmkey" }
tpm2-vtpm = { version = "1.2.3", path = "crates/vtpm" }
