[package]
authors.workspace = true
description = "TPM 2.0 key ASN.1 file reader and writer"
edition.workspace = true
homepage.workspace = true
license = "MIT OR Apache-2.0"
name = "tpm2-tpmkey"
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
pem = "4.0"
rasn = "0.26"
strum = { version = "0.28", features = ["derive"] }
tpm2-protocol.workspace = true
