[package]
authors.workspace = true
description = "TPM 2.0 policy language interpreter"
edition.workspace = true
homepage.workspace = true
license = "MIT OR Apache-2.0"
name = "tpm2-policy-language"
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
hex = "0.4"
strum = { version = "0.28", features = ["derive"] }
tpm2-crypto.workspace = true
tpm2-protocol.workspace = true

[dev-dependencies]
rstest = "0.26"
