[package]
authors.workspace = true
description = "TPM 2.0 device interface"
edition.workspace = true
homepage.workspace = true
license = "MIT OR Apache-2.0"
name = "tpm2-device"
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
hex = "0.4"
log = "0.4"
nix = { version = "0.29", features = ["fs", "poll"] }
rand = "0.8"
strum = { version = "0.28", features = ["derive"] }
tpm2-crypto.workspace = true
tpm2-protocol.workspace = true
tracing = { version = "0.1", default-features = false }

[dev-dependencies]
rstest = "0.26"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
