[package]
authors.workspace = true
description = "TPM 2.0 command-line interface"
edition.workspace = true
homepage.workspace = true
license = "GPL-3.0-or-later"
name = "tpm2sh"
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "tpm2sh"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
argh = { version = "0.1", default-features = false, features = ["help"] }
ctrlc = "3.4"
directories = "6.0"
env_logger = { version = "0.11", default-features = false }
hex = "0.4"
indicatif = { version = "0.17", default-features = false }
libc = "0.2.177"
log = "0.4"
nix = { version = "0.29", features = ["fs", "poll"] }
openssl = "0.10"
pem = "3.0"
strum = { version = "0.28", features = ["derive"] }
tabled = { version = "0.15", default-features = false, features = ["std", "derive", "ansi"] }
tpm2-crypto.workspace = true
tpm2-device.workspace = true
tpm2-policy-language.workspace = true
tpm2-protocol.workspace = true
tpm2-tpmkey.workspace = true
tpm2-vtpm.workspace = true

[dev-dependencies]
assert_cmd = "2.0"
duct = "0.13"
predicates = "3.0"
rstest = "0.23"
tempfile = "3.10"

[[test]]
name = "integration"
path = "tests/integration.rs"
harness = true
